# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://dwbig4e.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "dwbig4e"
description: dwbig4e

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: dwbig4e
author-bio: nothing
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Works
  permalink: works
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: https://instagram.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: dwbig4e"

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
